
import java.awt.Color;
import java.awt.Font;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Notepad extends javax.swing.JFrame {

    /**
     * Creates new form Notepad
     */
    public Notepad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Mood = new javax.swing.JComboBox<>();
        Frontcb = new javax.swing.JComboBox<>();
        Printbtn = new javax.swing.JButton();
        Savebtn = new javax.swing.JButton();
        Sizecb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        Resetbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        Mood.setBackground(new java.awt.Color(255, 255, 255));
        Mood.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mood.setForeground(new java.awt.Color(102, 102, 0));
        Mood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Light Mood", "Dark Mood" }));
        Mood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoodActionPerformed(evt);
            }
        });

        Frontcb.setBackground(new java.awt.Color(255, 255, 255));
        Frontcb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Frontcb.setForeground(new java.awt.Color(102, 102, 0));
        Frontcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Times New Roman", "Italian" }));
        Frontcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrontcbActionPerformed(evt);
            }
        });

        Printbtn.setBackground(new java.awt.Color(0, 0, 102));
        Printbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Printbtn.setForeground(new java.awt.Color(255, 255, 51));
        Printbtn.setText("Print");
        Printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintbtnActionPerformed(evt);
            }
        });

        Savebtn.setBackground(new java.awt.Color(255, 51, 51));
        Savebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Savebtn.setForeground(new java.awt.Color(255, 255, 51));
        Savebtn.setText("Save");
        Savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtnActionPerformed(evt);
            }
        });

        Sizecb.setBackground(new java.awt.Color(255, 255, 255));
        Sizecb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Sizecb.setForeground(new java.awt.Color(102, 102, 0));
        Sizecb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "15", "20", "25", "30", "35", "40", "45", "50" }));
        Sizecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SizecbActionPerformed(evt);
            }
        });

        ta.setBackground(new java.awt.Color(255, 255, 255));
        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        Resetbtn.setBackground(new java.awt.Color(0, 51, 51));
        Resetbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Resetbtn.setForeground(new java.awt.Color(255, 255, 51));
        Resetbtn.setText("Reset");
        Resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Sizecb, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(Frontcb, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(Mood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Resetbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Savebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Printbtn)))
                .addGap(24, 24, 24))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Frontcb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sizecb, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Printbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Savebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Resetbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrintbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintbtnActionPerformed
        try {
            // TODO add your handling code here:
            ta.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Notepad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PrintbtnActionPerformed

    private void SavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtnActionPerformed
                  
       try{
           FileOutStream f1 = new FileOutStream("E:\\paper.txt");
           String Data = ta.getText();
           f1.write(f1);
           f1.close(f1);
           
       }catch(Exception e){
         System.out.println(e);
       }
        
    }//GEN-LAST:event_SavebtnActionPerformed

    private void MoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoodActionPerformed
        // TODO add your handling code here:
        
        if(Mood.getSelectedItem() == "Dark Mood"){
             Mood.setBackground(Color.BLACK);
             Frontcb.setBackground(Color.BLACK);
             Sizecb.setBackground(Color.BLACK);
             ta.setBackground(Color.BLACK);
             jPanel2.setBackground(Color.BLACK);  
             ta.setForeground(Color.WHITE);
        }else if(Mood.getSelectedItem() == "Light Mood"){
              Mood.setBackground(Color.WHITE);
             Frontcb.setBackground(Color.WHITE);
             Sizecb.setBackground(Color.WHITE);
             ta.setBackground(Color.WHITE);
             jPanel2.setBackground(Color.WHITE); 
             ta.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_MoodActionPerformed

    private void FrontcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrontcbActionPerformed
        // TODO add your handling code here:
        
        if(Frontcb.getSelectedItem() == "Nomal"){
              ta.setFont(new Font("Arial",Font.PLAIN,12));
        }else if(Frontcb.getSelectedItem() == "Times New Roman"){
              ta.setFont(new Font("Times New Roman", Font.PLAIN, 12));
        }else if(Frontcb.getSelectedItem() == "Italian"){
            ta.setFont(new Font("Times New Roman", Font.ITALIC, 12));
        }
    }//GEN-LAST:event_FrontcbActionPerformed

    private void SizecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizecbActionPerformed
        // TODO add your handling code here:
        int[] iteam = {12,15,20,25,30,35,40,45,50};
             if(Sizecb.getSelectedIndex() == 0){
                ta.setFont(new Font("", Font.PLAIN, 12));
             }else if(Sizecb.getSelectedIndex() == 1){
                ta.setFont(new Font("", Font.PLAIN, 15));
             }else if(Sizecb.getSelectedIndex() == 2){
              ta.setFont(new Font("", Font.PLAIN, 20));
             }else if(Sizecb.getSelectedIndex() == 3){
              ta.setFont(new Font("", Font.PLAIN, 25));
             }else if(Sizecb.getSelectedIndex() == 4){
               ta.setFont(new Font("", Font.PLAIN, 30));
             }else if(Sizecb.getSelectedIndex() == 5){
               ta.setFont(new Font("", Font.PLAIN, 35));
             }else if(Sizecb.getSelectedIndex() == 6){
              ta.setFont(new Font("", Font.PLAIN, 40));
             }else if(Sizecb.getSelectedIndex() == 7){
              ta.setFont(new Font("", Font.ITALIC, 45));
             }else if(Sizecb.getSelectedIndex() == 8){
              ta.setFont(new Font("", Font.PLAIN, 50));
             }
    }//GEN-LAST:event_SizecbActionPerformed

    private void ResetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetbtnActionPerformed
        // TODO add your handling code here:
        ta.setText("");
    }//GEN-LAST:event_ResetbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notepad().setVisible(true);
                new Notepad().setTitle("AR Text Editor");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Frontcb;
    private javax.swing.JComboBox<String> Mood;
    private javax.swing.JButton Printbtn;
    private javax.swing.JButton Resetbtn;
    private javax.swing.JButton Savebtn;
    private javax.swing.JComboBox<String> Sizecb;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
}
